name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ${{ github.workspace }}/../private.key
          sudo chmod 600 ${{ github.workspace }}/../private.key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: deploy on production
        env:
          CMD: |
            cd $SSH_PROJECT_PATH
            git pull
            echo "${{secrets.MYSQL_ROOT_PASSWORD}}" > mysql_root_password.txt
            echo "${{secrets.ENV}}" > .env
            echo "${{secrets.CONFIG}}" > config.yaml
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_PROJECT_PATH: ${{secrets.SSH_PATH}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ github.workspace }}/../private.key $SSH_USER@$SSH_HOST -p $SSH_PORT "$CMD"
        shell: bash
